title: 腾讯·大家 存档
description: web.archive.org 中 dajia.qq.com 历史文章存档
url: "https://lishuhang.me"
baseurl: "/dajia"
timezone: Asia/Shanghai
lang: zh-CN

permalink: /posts/:title/

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - scripts/
  - _assets/
  - .github/
  - year/_template.md
